// Date: 2013/06/15 11:58:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer headwear;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer ribbon;
    ModelRenderer ribbon;
    ModelRenderer headwear2;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer chest;
    ModelRenderer skirt1;
    ModelRenderer skirt2;
    ModelRenderer skirt3;
    ModelRenderer skirt4;
    ModelRenderer rightwear;
    ModelRenderer rightring;
    ModelRenderer leftwear;
    ModelRenderer leftring;
  
  public ModelModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, -12F, 0F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      headwear = new ModelRenderer(this, 32, 0);
      headwear.addBox(-4F, -8F, -4F, 8, 8, 8);
      headwear.setRotationPoint(0F, -12F, 0F);
      headwear.setTextureSize(128, 128);
      headwear.mirror = true;
      setRotation(headwear, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 40);
      body.addBox(-4F, 0F, -2F, 8, 7, 4);
      body.setRotationPoint(0F, -12F, 0F);
      body.setTextureSize(128, 128);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 16, 16);
      rightarm.addBox(-3F, -1F, -1.5F, 3, 14, 3);
      rightarm.setRotationPoint(-4F, -10F, 0F);
      rightarm.setTextureSize(128, 128);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 16, 16);
      leftarm.addBox(-1F, -1F, -1.5F, 3, 14, 3);
      leftarm.setRotationPoint(5F, -10F, 0F);
      leftarm.setTextureSize(128, 128);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 20, 4);
      rightleg.setRotationPoint(-2F, 4F, 0F);
      rightleg.setTextureSize(128, 128);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 20, 4);
      leftleg.setRotationPoint(2F, 4F, 0F);
      leftleg.setTextureSize(128, 128);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      
      ribbon = new ModelRenderer(this, 64, 17);
      ribbon.addBox(-7F, -1F, 0F, 11, 4, 1);
      ribbon.setRotationPoint(0F, -20F, 4F);
      ribbon.setTextureSize(128, 128);
      ribbon.mirror = true;
      setRotation(ribbon, 0.5205006F, 0F, -0.3717861F);
      
      ribbon = new ModelRenderer(this, 64, 17);
      ribbon.addBox(-4F, -1F, 0F, 11, 4, 1);
      ribbon.setRotationPoint(0F, -20F, 4F);
      ribbon.setTextureSize(128, 128);
      ribbon.mirror = true;
      setRotation(ribbon, 0.5205006F, 0F, 0.3717861F);
      
      headwear2 = new ModelRenderer(this, 64, 0);
      headwear2.addBox(-4F, -1F, -4F, 8, 9, 8);
      headwear2.setRotationPoint(0F, -12F, 0F);
      headwear2.setTextureSize(128, 128);
      headwear2.mirror = true;
      setRotation(headwear2, 0.2602503F, 0F, 0F);
      
      body2 = new ModelRenderer(this, 0, 51);
      body2.addBox(-3F, 7F, -2F, 6, 5, 4);
      body2.setRotationPoint(0F, -12F, 0F);
      body2.setTextureSize(128, 128);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 0, 60);
      body3.addBox(-4F, 12F, -2F, 8, 4, 5);
      body3.setRotationPoint(0F, -12F, 0F);
      body3.setTextureSize(128, 128);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      
      chest = new ModelRenderer(this, 28, 16);
      chest.addBox(-4F, 1.6F, -1.5F, 8, 5, 2);
      chest.setRotationPoint(0F, -12F, 0F);
      chest.setTextureSize(128, 128);
      chest.mirror = true;
      setRotation(chest, -0.3839724F, 0F, 0F);
      
      skirt1 = new ModelRenderer(this, 0, 69);
      skirt1.addBox(-5F, 15F, -3F, 10, 1, 7);
      skirt1.setRotationPoint(0F, -12F, 0F);
      skirt1.setTextureSize(128, 128);
      skirt1.mirror = true;
      setRotation(skirt1, 0F, 0F, 0F);
      
      skirt2 = new ModelRenderer(this, 0, 77);
      skirt2.addBox(-6F, 16F, -4F, 12, 2, 9);
      skirt2.setRotationPoint(0F, -12F, 0F);
      skirt2.setTextureSize(128, 128);
      skirt2.mirror = true;
      setRotation(skirt2, 0F, 0F, 0F);
      
      skirt3 = new ModelRenderer(this, 0, 88);
      skirt3.addBox(-7F, 18F, -5F, 14, 3, 11);
      skirt3.setRotationPoint(0F, -12F, 0F);
      skirt3.setTextureSize(128, 128);
      skirt3.mirror = true;
      setRotation(skirt3, 0F, 0F, 0F);
      
      skirt4 = new ModelRenderer(this, 0, 102);
      skirt4.addBox(-8F, 21F, -6F, 16, 4, 13);
      skirt4.setRotationPoint(0F, -12F, 0F);
      skirt4.setTextureSize(128, 128);
      skirt4.mirror = true;
      setRotation(skirt4, 0F, 0F, 0F);
      
      rightwear = new ModelRenderer(this, 28, 23);
      rightwear.addBox(-4.6F, -2F, -2F, 5, 4, 4);
      rightwear.setRotationPoint(-4F, -10F, 0F);
      rightwear.setTextureSize(128, 128);
      rightwear.mirror = true;
      setRotation(rightwear, 0F, 0F, -0.2230717F);
      
      rightring = new ModelRenderer(this, 28, 31);
      rightring.addBox(-3F, 10F, -1.5F, 3, 1, 3);
      rightring.setRotationPoint(-4F, -10F, 0F);
      rightring.setTextureSize(128, 128);
      rightring.mirror = true;
      setRotation(rightring, 0F, 0F, 0F);
      
      leftwear = new ModelRenderer(this, 28, 23);
      leftwear.addBox(-0.4F, -2F, -2F, 5, 4, 4);
      leftwear.setRotationPoint(4F, -10F, 0F);
      leftwear.setTextureSize(128, 128);
      leftwear.mirror = true;
      setRotation(leftwear, 0F, 0F, 0.2230717F);
      
      leftring = new ModelRenderer(this, 28, 31);
      leftring.addBox(0F, 10F, -1.5F, 3, 1, 3);
      leftring.setRotationPoint(4F, -10F, 0F);
      leftring.setTextureSize(128, 128);
      leftring.mirror = true;
      setRotation(leftring, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    headwear.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    ribbon.render(f5);
    ribbon.render(f5);
    headwear2.render(f5);
    body2.render(f5);
    body3.render(f5);
    chest.render(f5);
    skirt1.render(f5);
    skirt2.render(f5);
    skirt3.render(f5);
    skirt4.render(f5);
    rightwear.render(f5);
    rightring.render(f5);
    leftwear.render(f5);
    leftring.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
