// Date: 2013/06/11 21:03:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer hair1;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer skirt1;
    ModelRenderer skrit2;
    ModelRenderer skrit3;
    ModelRenderer chest;
    ModelRenderer hat1;
    ModelRenderer hat2;
    ModelRenderer hat3;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -6F, -3F, 6, 6, 6);
      head.setRotationPoint(0F, 8F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      hair1 = new ModelRenderer(this, 24, 0);
      hair1.addBox(-3F, -6F, -3F, 6, 6, 6);
      hair1.setRotationPoint(0F, 8F, 0F);
      hair1.setTextureSize(64, 64);
      hair1.mirror = true;
      setRotation(hair1, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 12);
      body.addBox(-3F, 0F, -1.5F, 6, 7, 3);
      body.setRotationPoint(0F, 8F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 30, 12);
      rightarm.addBox(-2F, -1F, -1F, 2, 7, 2);
      rightarm.setRotationPoint(-3F, 9F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.1115358F);
      leftarm = new ModelRenderer(this, 30, 12);
      leftarm.addBox(0F, -1F, -1F, 2, 7, 2);
      leftarm.setRotationPoint(3F, 9F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.1115358F);
      rightleg = new ModelRenderer(this, 18, 12);
      rightleg.addBox(-3F, 0F, -1.5F, 3, 8, 3);
      rightleg.setRotationPoint(0F, 16F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 18, 12);
      leftleg.addBox(0F, 0F, -1.5F, 3, 8, 3);
      leftleg.setRotationPoint(0F, 16F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      skirt1 = new ModelRenderer(this, 0, 29);
      skirt1.addBox(-3F, 0F, -2F, 6, 1, 4);
      skirt1.setRotationPoint(0F, 14F, 0F);
      skirt1.setTextureSize(64, 64);
      skirt1.mirror = true;
      
      setRotation(skirt1, 0F, 0F, 0F);
      skrit2 = new ModelRenderer(this, 0, 34);
      skrit2.addBox(-4F, 0F, -3F, 8, 2, 6);
      skrit2.setRotationPoint(0F, 15F, 0F);
      skrit2.setTextureSize(64, 64);
      skrit2.mirror = true;
      setRotation(skrit2, 0F, 0F, 0F);
      
      skrit3 = new ModelRenderer(this, 0, 42);
      skrit3.addBox(-5F, 0F, -4F, 10, 3, 8);
      skrit3.setRotationPoint(0F, 17F, 0F);
      skrit3.setTextureSize(64, 64);
      skrit3.mirror = true;
      setRotation(skrit3, 0F, 0F, 0F);
      
      chest = new ModelRenderer(this, 0, 24);
      chest.addBox(-3F, 1.5F, -1F, 6, 3, 2);
      chest.setRotationPoint(0F, 8F, 0F);
      chest.setTextureSize(64, 64);
      chest.mirror = true;
      setRotation(chest, -0.3490659F, 0F, 0F);
      
      hat1 = new ModelRenderer(this, 22, 23);
      hat1.addBox(-5F, -4.5F, -6F, 10, 1, 11);
      hat1.setRotationPoint(0F, 8F, 0F);
      hat1.setTextureSize(64, 64);
      hat1.mirror = true;
      setRotation(hat1, -0.1487144F, 0F, 0F);
      
      hat2 = new ModelRenderer(this, 38, 12);
      hat2.addBox(-2F, -7.5F, -3F, 4, 3, 5);
      hat2.setRotationPoint(0F, 8F, 0F);
      hat2.setTextureSize(64, 64);
      hat2.mirror = true;
      setRotation(hat2, -0.1858931F, 0F, 0F);
      
      hat3 = new ModelRenderer(this, 48, 5);
      hat3.addBox(-1F, -8.5F, -2F, 2, 1, 5);
      hat3.setRotationPoint(0F, 8F, 0F);
      hat3.setTextureSize(64, 64);
      hat3.mirror = true;
      setRotation(hat3, -0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    hair1.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    skirt1.render(f5);
    skrit2.render(f5);
    skrit3.render(f5);
    chest.render(f5);
    hat1.render(f5);
    hat2.render(f5);
    hat3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
