// Date: 2013/06/13 22:17:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer hair1;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer skirt1;
    ModelRenderer skrit2;
    ModelRenderer skrit3;
    ModelRenderer chest;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer tail6;
    ModelRenderer tail7;
    ModelRenderer tail8;
    ModelRenderer tail9;
    ModelRenderer rightear;
    ModelRenderer leftear;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -6F, -3F, 6, 6, 6);
      head.setRotationPoint(0F, 6F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      hair1 = new ModelRenderer(this, 24, 0);
      hair1.addBox(-3F, -6F, -3F, 6, 6, 6);
      hair1.setRotationPoint(0F, 6F, 0F);
      hair1.setTextureSize(64, 64);
      hair1.mirror = true;
      setRotation(hair1, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 12);
      body.addBox(-3F, 0F, -1.5F, 6, 8, 3);
      body.setRotationPoint(0F, 6F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 30, 12);
      rightarm.addBox(-2F, -1F, -1F, 2, 7, 2);
      rightarm.setRotationPoint(-3F, 7F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.1115358F);
      leftarm = new ModelRenderer(this, 30, 12);
      leftarm.addBox(0F, -1F, -1F, 2, 7, 2);
      leftarm.setRotationPoint(3F, 7F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.1115358F);
      rightleg = new ModelRenderer(this, 18, 12);
      rightleg.addBox(-3F, 0F, -1.5F, 3, 9, 3);
      rightleg.setRotationPoint(0F, 15F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 18, 12);
      leftleg.addBox(0F, 0F, -1.5F, 3, 9, 3);
      leftleg.setRotationPoint(0F, 15F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      skirt1 = new ModelRenderer(this, 0, 29);
      skirt1.addBox(-3F, 0F, -2F, 6, 1, 4);
      skirt1.setRotationPoint(0F, 12F, 0F);
      skirt1.setTextureSize(64, 64);
      skirt1.mirror = true;
      setRotation(skirt1, 0F, 0F, 0F);
      skrit2 = new ModelRenderer(this, 0, 34);
      skrit2.addBox(-4F, 0F, -3F, 8, 3, 6);
      skrit2.setRotationPoint(0F, 13F, 0F);
      skrit2.setTextureSize(64, 64);
      skrit2.mirror = true;
      setRotation(skrit2, 0F, 0F, 0F);
      skrit3 = new ModelRenderer(this, 0, 43);
      skrit3.addBox(-5F, 0F, -4F, 10, 5, 8);
      skrit3.setRotationPoint(0F, 16F, 0F);
      skrit3.setTextureSize(64, 64);
      skrit3.mirror = true;
      setRotation(skrit3, 0F, 0F, 0F);
      chest = new ModelRenderer(this, 0, 24);
      chest.addBox(-3F, 1.2F, -1F, 6, 3, 2);
      chest.setRotationPoint(0F, 6F, 0F);
      chest.setTextureSize(64, 64);
      chest.mirror = true;
      setRotation(chest, -0.5919179F, 0F, 0F);
      tail1 = new ModelRenderer(this, 38, 12);
      tail1.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail1.setRotationPoint(0F, 12F, 2F);
      tail1.setTextureSize(64, 64);
      tail1.mirror = true;
      setRotation(tail1, 0.4833219F, 0F, -0.4363323F);
      tail2 = new ModelRenderer(this, 38, 12);
      tail2.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail2.setRotationPoint(0F, 12F, 2F);
      tail2.setTextureSize(64, 64);
      tail2.mirror = true;
      setRotation(tail2, 0.4833219F, 0F, 2.617994F);
      tail3 = new ModelRenderer(this, 38, 12);
      tail3.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail3.setRotationPoint(0F, 12F, 1F);
      tail3.setTextureSize(64, 64);
      tail3.mirror = true;
      setRotation(tail3, 0.4833219F, 0F, 1.745329F);
      tail4 = new ModelRenderer(this, 38, 12);
      tail4.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail4.setRotationPoint(0F, 12F, 2F);
      tail4.setTextureSize(64, 64);
      tail4.mirror = true;
      setRotation(tail4, 0.4833219F, 0F, -2.617994F);
      tail5 = new ModelRenderer(this, 38, 12);
      tail5.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail5.setRotationPoint(0F, 12F, 2F);
      tail5.setTextureSize(64, 64);
      tail5.mirror = true;
      setRotation(tail5, 0.4833219F, 0F, -1.745329F);
      tail6 = new ModelRenderer(this, 38, 12);
      tail6.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail6.setRotationPoint(0F, 12F, 2F);
      tail6.setTextureSize(64, 64);
      tail6.mirror = true;
      setRotation(tail6, 0.8179294F, 0F, 0.9599311F);
      tail7 = new ModelRenderer(this, 38, 12);
      tail7.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail7.setRotationPoint(0F, 12F, 2F);
      tail7.setTextureSize(64, 64);
      tail7.mirror = true;
      setRotation(tail7, 0.9294653F, 0F, 3.141593F);
      tail8 = new ModelRenderer(this, 38, 12);
      tail8.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail8.setRotationPoint(0F, 12F, 2F);
      tail8.setTextureSize(64, 64);
      tail8.mirror = true;
      setRotation(tail8, 0.8179294F, 0F, -0.9599311F);
      tail9 = new ModelRenderer(this, 38, 12);
      tail9.addBox(-1.5F, 0F, -1.5F, 3, 8, 3);
      tail9.setRotationPoint(0F, 12F, 2F);
      tail9.setTextureSize(64, 64);
      tail9.mirror = true;
      setRotation(tail9, 0.4833219F, 0F, 0.4363323F);
      rightear = new ModelRenderer(this, 48, 0);
      rightear.addBox(-2F, -2F, -1F, 2, 2, 1);
      rightear.setRotationPoint(0F, 0F, 0F);
      rightear.setTextureSize(64, 64);
      rightear.mirror = true;
      setRotation(rightear, 0F, 0F, -0.7853982F);
      leftear = new ModelRenderer(this, 48, 0);
      leftear.addBox(0F, 0F, -1F, 2, 2, 1);
      leftear.setRotationPoint(0F, 0F, 0F);
      leftear.setTextureSize(64, 64);
      leftear.mirror = true;
      setRotation(leftear, 0F, 0F, -0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    hair1.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    skirt1.render(f5);
    skrit2.render(f5);
    skrit3.render(f5);
    chest.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    tail3.render(f5);
    tail4.render(f5);
    tail5.render(f5);
    tail6.render(f5);
    tail7.render(f5);
    tail8.render(f5);
    tail9.render(f5);
    rightear.render(f5);
    leftear.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
