// Date: 2013/06/08 13:19:47
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer bipedHead;
    ModelRenderer bipedBody;
    ModelRenderer bipedRightArm;
    ModelRenderer bipedLeftArm;
    ModelRenderer bipedRightLeg;
    ModelRenderer bipedLeftLeg;
    ModelRenderer skirt1;
    ModelRenderer skrit2;
    ModelRenderer skrit3;
    ModelRenderer chest;
    ModelRenderer hair1;
    ModelRenderer hair2;
    ModelRenderer ribbon;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      bipedHead = new ModelRenderer(this, 0, 0);
      bipedHead.addBox(-3F, -6F, -3F, 6, 6, 6);
      bipedHead.setRotationPoint(0F, 8F, 0F);
      bipedHead.setTextureSize(64, 64);
      bipedHead.mirror = true;
      setRotation(bipedHead, 0F, 0F, 0F);
      bipedBody = new ModelRenderer(this, 0, 12);
      bipedBody.addBox(-3F, 0F, -1.5F, 6, 7, 3);
      bipedBody.setRotationPoint(0F, 8F, 0F);
      bipedBody.setTextureSize(64, 64);
      bipedBody.mirror = true;
      setRotation(bipedBody, 0F, 0F, 0F);
      bipedRightArm = new ModelRenderer(this, 30, 12);
      bipedRightArm.addBox(-2F, -1F, -1F, 2, 7, 2);
      bipedRightArm.setRotationPoint(-3F, 9F, 0F);
      bipedRightArm.setTextureSize(64, 64);
      bipedRightArm.mirror = true;
      setRotation(bipedRightArm, 0F, 0F, 0.1115358F);
      bipedLeftArm = new ModelRenderer(this, 30, 12);
      bipedLeftArm.addBox(0F, -1F, -1F, 2, 7, 2);
      bipedLeftArm.setRotationPoint(3F, 9F, 0F);
      bipedLeftArm.setTextureSize(64, 64);
      bipedLeftArm.mirror = true;
      setRotation(bipedLeftArm, 0F, 0F, -0.1115358F);
      bipedRightLeg = new ModelRenderer(this, 18, 12);
      bipedRightLeg.addBox(-3F, 0F, -1.5F, 3, 8, 3);
      bipedRightLeg.setRotationPoint(0F, 16F, 0F);
      bipedRightLeg.setTextureSize(64, 64);
      bipedRightLeg.mirror = true;
      setRotation(bipedRightLeg, 0F, 0F, 0F);
      bipedLeftLeg = new ModelRenderer(this, 18, 12);
      bipedLeftLeg.addBox(0F, 0F, -1.5F, 3, 8, 3);
      bipedLeftLeg.setRotationPoint(0F, 16F, 0F);
      bipedLeftLeg.setTextureSize(64, 64);
      bipedLeftLeg.mirror = true;
      setRotation(bipedLeftLeg, 0F, 0F, 0F);
      skirt1 = new ModelRenderer(this, 0, 29);
      skirt1.addBox(-3F, 0F, -2F, 6, 1, 4);
      skirt1.setRotationPoint(0F, 15F, 0F);
      skirt1.setTextureSize(64, 64);
      skirt1.mirror = true;
      setRotation(skirt1, 0F, 0F, 0F);
      skrit2 = new ModelRenderer(this, 0, 34);
      skrit2.addBox(-4F, 0F, -3F, 8, 2, 6);
      skrit2.setRotationPoint(0F, 16F, 0F);
      skrit2.setTextureSize(64, 64);
      skrit2.mirror = true;
      setRotation(skrit2, 0F, 0F, 0F);
      skrit3 = new ModelRenderer(this, 0, 42);
      skrit3.addBox(-5F, 0F, -4F, 10, 3, 8);
      skrit3.setRotationPoint(0F, 18F, 0F);
      skrit3.setTextureSize(64, 64);
      skrit3.mirror = true;
      setRotation(skrit3, 0F, 0F, 0F);
      chest = new ModelRenderer(this, 0, 24);
      chest.addBox(-3F, 1.5F, -1F, 6, 3, 2);
      chest.setRotationPoint(0F, 8F, 0F);
      chest.setTextureSize(64, 64);
      chest.mirror = true;
      setRotation(chest, -0.3490659F, 0F, 0F);
      hair1 = new ModelRenderer(this, 24, 0);
      hair1.addBox(-3F, -6F, -3F, 6, 6, 6);
      hair1.setRotationPoint(0F, 8F, 0F);
      hair1.setTextureSize(64, 64);
      hair1.mirror = true;
      setRotation(hair1, 0F, 0F, 0F);
      hair2 = new ModelRenderer(this, 38, 12);
      hair2.addBox(-1F, -1F, 0F, 2, 1, 6);
      hair2.setRotationPoint(0F, 2F, 4F);
      hair2.setTextureSize(64, 64);
      hair2.mirror = true;
      setRotation(hair2, -1.412787F, 0F, 0F);
      ribbon = new ModelRenderer(this, 38, 19);
      ribbon.addBox(-4F, -1F, -1F, 8, 1, 4);
      ribbon.setRotationPoint(0F, 2F, 3F);
      ribbon.setTextureSize(64, 64);
      ribbon.mirror = true;
      setRotation(ribbon, -1.163009F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bipedHead.render(f5);
    bipedBody.render(f5);
    bipedRightArm.render(f5);
    bipedLeftArm.render(f5);
    bipedRightLeg.render(f5);
    bipedLeftLeg.render(f5);
    skirt1.render(f5);
    skrit2.render(f5);
    skrit3.render(f5);
    chest.render(f5);
    hair1.render(f5);
    hair2.render(f5);
    ribbon.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
