// Date: 2013/06/09 11:05:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer hair1;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer skirt1;
    ModelRenderer skirt2;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer chest;
    ModelRenderer rightear;
    ModelRenderer leftear;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -6F, -3F, 6, 6, 6);
      head.setRotationPoint(0F, 8F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      hair1 = new ModelRenderer(this, 24, 0);
      hair1.addBox(-3F, -6F, -3F, 6, 6, 6);
      hair1.setRotationPoint(0F, 8F, 0F);
      hair1.setTextureSize(64, 64);
      hair1.mirror = true;
      setRotation(hair1, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 12);
      body.addBox(-3F, 0F, -1.5F, 6, 7, 3);
      body.setRotationPoint(0F, 8F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 30, 12);
      rightarm.addBox(-2F, -1F, -1F, 2, 7, 2);
      rightarm.setRotationPoint(-3F, 9F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.1115358F);
      leftarm = new ModelRenderer(this, 30, 12);
      leftarm.addBox(0F, -1F, -1F, 2, 7, 2);
      leftarm.setRotationPoint(3F, 9F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.1115358F);
      rightleg = new ModelRenderer(this, 18, 12);
      rightleg.addBox(-3F, 0F, -1.5F, 3, 8, 3);
      rightleg.setRotationPoint(0F, 16F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 18, 12);
      leftleg.addBox(0F, 0F, -1.5F, 3, 8, 3);
      leftleg.setRotationPoint(0F, 16F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      
      skirt1 = new ModelRenderer(this, 0, 29);
      skirt1.addBox(-3.033333F, 0F, -2F, 6, 1, 5);
      skirt1.setRotationPoint(0F, 15F, 0F);
      skirt1.setTextureSize(64, 64);
      skirt1.mirror = true;
      setRotation(skirt1, 0F, 0F, 0F);
      
      skirt2 = new ModelRenderer(this, 0, 34);
      skirt2.addBox(-4F, 0F, -3F, 8, 2, 6);
      skirt2.setRotationPoint(0F, 16F, 1F);
      skirt2.setTextureSize(64, 64);
      skirt2.mirror = true;
      setRotation(skirt2, 0F, 0F, 0F);
      
      tail1 = new ModelRenderer(this, 0, 42);
      tail1.addBox(-3F, 0F, -4F, 6, 7, 5);
      tail1.setRotationPoint(0F, 16F, 2F);
      tail1.setTextureSize(64, 64);
      tail1.mirror = true;
      setRotation(tail1, 0.2617994F, 0F, 0F);
      
      tail2 = new ModelRenderer(this, 22, 42);
      tail2.addBox(-2F, 0F, 0F, 4, 4, 7);
      tail2.setRotationPoint(0F, 20F, 0F);
      tail2.setTextureSize(64, 64);
      tail2.mirror = true;
      setRotation(tail2, 0F, 0F, 0F);
      
      tail3 = new ModelRenderer(this, 0, 54);
      tail3.addBox(-1.5F, -1.5F, 0F, 3, 3, 4);
      tail3.setRotationPoint(0F, 22F, 6F);
      tail3.setTextureSize(64, 64);
      tail3.mirror = true;
      setRotation(tail3, 0.3717861F, 0F, 0F);
      
      tail4 = new ModelRenderer(this, 14, 54);
      tail4.addBox(-4F, 0F, 1F, 8, 1, 4);
      tail4.setRotationPoint(0F, 21F, 7F);
      tail4.setTextureSize(64, 64);
      tail4.mirror = true;
      setRotation(tail4, 0.4461433F, 0F, 0F);
      
      chest = new ModelRenderer(this, 0, 24);
      chest.addBox(-3F, 1.5F, -1F, 6, 3, 2);
      chest.setRotationPoint(0F, 8F, 0F);
      chest.setTextureSize(64, 64);
      chest.mirror = true;
      setRotation(chest, -0.3490659F, 0F, 0F);
      
      rightear = new ModelRenderer(this, 48, 0);
      rightear.addBox(-2.5F, -1F, -1F, 2, 1, 3);
      rightear.setRotationPoint(-2F, 5F, -1F);
      rightear.setTextureSize(64, 64);
      rightear.mirror = true;

      setRotation(rightear, -1.329122F, 0F, -0.4461433F);
      leftear = new ModelRenderer(this, 48, 0);
      leftear.addBox(0F, -1F, -1F, 2, 1, 3);
      leftear.setRotationPoint(2.5F, 5F, -1F);
      leftear.setTextureSize(64, 64);
      leftear.mirror = true;
      setRotation(leftear, -1.329121F, 0F, 0.4461411F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    hair1.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    skirt1.render(f5);
    skirt2.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    tail3.render(f5);
    tail4.render(f5);
    chest.render(f5);
    rightear.render(f5);
    leftear.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
